### PR TITLE
Deprecate topology policies

### LINKED ISSUE #630: update the codebase to stop using NRT.topologyPolicies
Starting the API v1alpha2, the `topologyPolicies` field is deprecated and should not be used. The new recommended approach is to use the attributes. Still our codebase (most notably test) use that field:
```
$ git grep -i topologypolicies
internal/noderesourcetopology/tostring.go:64:   if len(nrt.TopologyPolicies) > 0 {
internal/noderesourcetopology/tostring.go:65:           pol = nrt.TopologyPolicies[0]
internal/noderesourcetopology/tostring_test.go:177:                             TopologyPolicies: []string{
test/e2e/serial/tests/non_regression.go:286:                    policyFuncs := tmPolicyFuncsHandler[nrtv1alpha2.TopologyManagerPolicy(nrtInitial.TopologyPolicies[0])]
test/e2e/serial/tests/resource_accounting.go:521:                       if targetNrtInitial.TopologyPolicies[0] == string(nrtv1alpha2.SingleNUMANodePodLevel) {
test/e2e/serial/tests/resource_accounting.go:648:                       policyFuncs := tmPolicyFuncsHandler[nrtv1alpha2.TopologyManagerPolicy(targetNrtInitial.TopologyPolicies[0])]
test/e2e/serial/tests/workload_placement.go:251:                        policyFuncs := tmPolicyFuncsHandler[nrtv1alpha2.TopologyManagerPolicy(nrtInitial.TopologyPolicies[0])]
test/e2e/serial/tests/workload_placement.go:493:                        tmPolicy := nrtv1alpha2.TopologyManagerPolicy(nrtInitial.TopologyPolicies[0])
test/e2e/serial/tests/workload_unschedulable.go:89:             tmPolicy = nrts[0].TopologyPolicies[0]
test/utils/noderesourcetopologies/noderesourcetopologies.go:327:                if !contains(nrt.TopologyPolicies, string(tmPolicy)) {
```

we need to update

### PR DESCRIPTION
**Pull request by jlojosnegros**
`topologyPolicies` field is deprecated and should not be used. 
The new recommended approach is to use the attributes. 
Update our codebase to use an attribute instead of that field.

Fixes #630

### CODE REVIEW

**Comment by ffromani** [comment]
we should stop using `topologyPolicies` entirely in our code entirely and replace it with the attribute scope/policy attribute pair. In addition, this helper package can probably help https://pkg.go.dev/github.com/k8stopologyawareschedwg/noderesourcetopology-api@v0.1.1/pkg/apis/topology/v1alpha2/helper/attribute

**Comment by ffromani** [comment]
(This work can be split in multiple PRs)

**Comment by jlojosnegros** [comment]
> we should stop using `topologyPolicies` entirely in our code entirely and replace it with the attribute scope/policy attribute pair. In addition, this helper package can probably help https://pkg.go.dev/github.com/k8stopologyawareschedwg/noderesourcetopology-api@v0.1.1/pkg/apis/topology/v1alpha2/helper/attribute

Thanks for pointing to the module. 
I have reworked the functions to use it.


Regarding the "stop using entirely" I think we are not using any more the field in the NRO, I just found some mentions in the RTE

```
14:21 $ git grep  TopologyPolicies
internal/noderesourcetopology/topology_policies.go:const TopologyPoliciesAttribute = "TopologyPolicies"
internal/noderesourcetopology/topology_policies.go:func GetTopologyPolicies(nrt nrtv1alpha2.NodeResourceTopology) []nrtv1alpha2.TopologyManagerPolicy {
internal/noderesourcetopology/topology_policies.go:     attr, ok := attribute.Get(nrt.Attributes, TopologyPoliciesAttribute)
internal/noderesourcetopology/topology_policies.go:func SetTopologyPolicies(nrt *nrtv1alpha2.NodeResourceTopology, topologyPolicies []nrtv1alpha2.TopologyManagerPolicy) error {
internal/noderesourcetopology/topology_policies.go:             Name:  TopologyPoliciesAttribute,
internal/noderesourcetopology/topology_policies.go:     attr, ok := attribute.Get(nrt.Attributes, TopologyPoliciesAttribute)
internal/noderesourcetopology/topology_policies.go:             Name:  TopologyPoliciesAttribute,
internal/noderesourcetopology/topology_policies_test.go:func TestTopologyPoliciesAttribute(t *testing.T) {
internal/noderesourcetopology/topology_policies_test.go:        err := SetTopologyPolicies(nrt, policies)
internal/noderesourcetopology/topology_policies_test.go:        actual := GetTopologyPolicies(*nrt)
internal/noderesourcetopology/topology_policies_test.go:        actual = GetTopologyPolicies(*nrt)
internal/noderesourcetopology/tostring.go:      topologies := GetTopologyPolicies(nrt)
internal/noderesourcetopology/tostring_test.go:                                         Name:  TopologyPoliciesAttribute,
test/e2e/serial/tests/non_regression.go:                        nrtInitialTopologyPolicies := noderesourcetopology.GetTopologyPolicies(*nrtInitial)
test/e2e/serial/tests/non_regression.go:                        policyFuncs := tmPolicyFuncsHandler[nrtv1alpha2.TopologyManagerPolicy(nrtInitialTopologyPolicies[0])]
test/e2e/serial/tests/resource_accounting.go:                   targetNrtInitialTopologyPolicies := noderesourcetopology.GetTopologyPolicies(*targetNrtInitial)
test/e2e/serial/tests/resource_accounting.go:                   if targetNrtInitialTopologyPolicies[0] == nrtv1alpha2.SingleNUMANodePodLevel {
test/e2e/serial/tests/resource_accounting.go:                   targetNrtInitialTopologyPolicies := noderesourcetopology.GetTopologyPolicies(*targetNrtInitial)
test/e2e/serial/tests/resource_accounting.go:                   policyFuncs := tmPolicyFuncsHandler[nrtv1alpha2.TopologyManagerPolicy(targetNrtInitialTopologyPolicies[0])]
test/e2e/serial/tests/workload_placement.go:                    nrtInitialTopologyPolicies := noderesourcetopology.GetTopologyPolicies(*nrtInitial)
test/e2e/serial/tests/workload_placement.go:                    policyFuncs := tmPolicyFuncsHandler[nrtInitialTopologyPolicies[0]]
test/e2e/serial/tests/workload_placement.go:                    nrtInitialTopologyPolicies := noderesourcetopology.GetTopologyPolicies(*nrtInitial)
test/e2e/serial/tests/workload_placement.go:                    tmPolicy := nrtInitialTopologyPolicies[0]
test/e2e/serial/tests/workload_unschedulable.go:                tps := noderesourcetopology.GetTopologyPolicies(nrts[0])
test/utils/noderesourcetopologies/noderesourcetopologies.go:            topologyPolicies := e2enrt.GetTopologyPolicies(nrt)
vendor/github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha1/types.go: TopologyPolicies []string `json:"topologyPolicies"`
vendor/github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha1/zz_generated.deepcopy.go: if in.TopologyPolicies != nil {
vendor/github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha1/zz_generated.deepcopy.go:         in, out := &in.TopologyPolicies, &out.TopologyPolicies
vendor/github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha2/types.go: TopologyPolicies []string `json:"topologyPolicies,omitempty"`
vendor/github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha2/zz_generated.deepcopy.go: if in.TopologyPolicies != nil {
vendor/github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha2/zz_generated.deepcopy.go:         in, out := &in.TopologyPolicies, &out.TopologyPolicies
vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/nrtupdater/nrtupdater.go:      nrt.TopologyPolicies = []string{te.tmPolicy}
vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/nodetopology/nodetopology.go:       if nodeTopology == nil || len(nodeTopology.TopologyPolicies) == 0 {
vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/nodetopology/nodetopology.go:       if nodeTopology.TopologyPolicies[0] != tmPolicy {
vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/nodetopology/nodetopology.go:               framework.Logf("topology mismatch got %q expected %q", nodeTopology.TopologyPolici>
```

I can address those in another PR in [RTE repo](https://github.com/k8stopologyawareschedwg/resource-topology-exporter)

File: internal/noderesourcetopology/tostring_test.go [hunk 1]
```diff
@@ -174,9 +174,11 @@ func TestToString(t *testing.T) {
...
 					Name: "test-nrt",
 				},
-				TopologyPolicies: []string{
-					"restricted",
-					"ignored-from-the-second-onwards",
+				Attributes: []nrtv1alpha2.AttributeInfo{
+					{
+						Name:  TopologyPoliciesAttribute,
+						Value: "restricted,ignored-from-the-second-onwards",
+					},
```
Comment (ffromani) [inline internal/noderesourcetopology/tostring_test.go:181]: even though this is not formally regulated, attributes are commonly key/value pairs. It's legal for the value to be a comma-separated list, but is out of the conventions. Most notably Having a list of values was the expected use case for `topologyPolicies` but is not relevant for attributes. I'd just remove this test.

File: test/e2e/serial/tests/non_regression.go [hunk 2]
```diff
@@ -283,7 +284,8 @@ var _ = Describe("[serial][disruptive][scheduler] numaresources workload placeme
 			nrtPostCreate, err := e2enrt.FindFromList(nrtPostCreateDeploymentList.Items, updatedPod.Spec.NodeName)
 			Expect(err).ToNot(HaveOccurred())
 
-			policyFuncs := tmPolicyFuncsHandler[nrtv1alpha2.TopologyManagerPolicy(nrtInitial.TopologyPolicies[0])]
+			nrtInitialTopologyPolicies := noderesourcetopology.GetTopologyPolicies(*nrtInitial)
+			policyFuncs := tmPolicyFuncsHandler[nrtv1alpha2.TopologyManagerPolicy(nrtInitialTopologyPolicies[0])]
```
Comment (ffromani) [inline test/e2e/serial/tests/non_regression.go:288]: again we should just pick the first attribute, possibly erroring out of there are more attributes

File: test/e2e/serial/tests/resource_accounting.go [hunk 3]
```diff
@@ -518,7 +519,8 @@ var _ = Describe("[serial][disruptive][scheduler][resacct] numaresources workloa
 			pod.Spec.Containers[0].Resources.Limits = reqResPerNUMA[0]
 			// keep the pod QoS as burstable
 			pod.Spec.Containers[1].Resources.Requests = reqResPerNUMA[1]
-			if targetNrtInitial.TopologyPolicies[0] == string(nrtv1alpha2.SingleNUMANodePodLevel) {
+			targetNrtInitialTopologyPolicies := noderesourcetopology.GetTopologyPolicies(*targetNrtInitial)
+			if targetNrtInitialTopologyPolicies[0] == nrtv1alpha2.SingleNUMANodePodLevel {
```
Comment (ffromani) [inline test/e2e/serial/tests/resource_accounting.go:523]: this value is unexpected for a topology policy attribute, doesn't seem right

File: test/e2e/serial/tests/resource_accounting.go [hunk 4]
```diff
@@ -645,7 +647,8 @@ var _ = Describe("[serial][disruptive][scheduler][resacct] numaresources workloa
 			rl := e2ereslist.FromGuaranteedPod(*updatedPod2)
 			klog.Infof("post-create pod resource list: spec=[%s] updated=[%s]", e2ereslist.ToString(e2ereslist.FromContainers(podGuanranteed.Spec.Containers)), e2ereslist.ToString(rl))
 
-			policyFuncs := tmPolicyFuncsHandler[nrtv1alpha2.TopologyManagerPolicy(targetNrtInitial.TopologyPolicies[0])]
+			targetNrtInitialTopologyPolicies := noderesourcetopology.GetTopologyPolicies(*targetNrtInitial)
+			policyFuncs := tmPolicyFuncsHandler[nrtv1alpha2.TopologyManagerPolicy(targetNrtInitialTopologyPolicies[0])]
```
Comment (ffromani) [inline test/e2e/serial/tests/resource_accounting.go:651]: I think `tmPolicyFuncsHandler` is keyed by the old `topologyPolicy` value, which doesn't (nor it should) directly translate to the policy/scope attribute pair (applies also elsewhere)

File: test/e2e/serial/tests/workload_unschedulable.go [hunk 5]
```diff
@@ -86,7 +87,8 @@ var _ = Describe("[serial][disruptive][scheduler] numaresources workload unsched
 		}
 
 		// we expect having the same policy across all NRTs
-		tmPolicy = nrts[0].TopologyPolicies[0]
+		tps := noderesourcetopology.GetTopologyPolicies(nrts[0])
+		tmPolicy = tps[0]
```
Comment (ffromani) [inline test/e2e/serial/tests/workload_unschedulable.go:91]: again just fetch the first attribute, possibly erroring out if there are duplicate attrs (which is again legal but uncommon/unexpected). The duplicated attributes check can probably generalized/made smarter

**Review by ffromani — COMMENTED** [review]
I think it's a nice start but likely many more changes are needed

**Comment by ffromani** [comment]
> > we should stop using `topologyPolicies` entirely in our code entirely and replace it with the attribute scope/policy attribute pair. In addition, this helper package can probably help https://pkg.go.dev/github.com/k8stopologyawareschedwg/noderesourcetopology-api@v0.1.1/pkg/apis/topology/v1alpha2/helper/attribute
> 
> Thanks for pointing to the module. I have reworked the functions to use it.
> 
> Regarding the "stop using entirely" I think we are not using any more the field in the NRO, I just found some mentions in the RTE

We need to update also all the code locations which use the _values_ encoded in `topologyPolicies`, so `SingleNUMANodeContainerLevel` or `SingleNUMANodePodLevel` (etc. etc.) 

We can split this work in multiple PRs though.

RTE will likely need to be updated indeed. Same goes for NFD.

File: test/e2e/serial/config/config.go [hunk 6]
```diff
@@ -30,6 +30,7 @@ import (
 	nrtv1alpha2 "github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha2"
 	nrtv1alpha2attr "github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha2/helper/attribute"
 
+	nrtp "github.com/openshift-kni/numaresources-operator/internal/noderesourcetopology"
```
Comment (ffromani) [inline test/e2e/serial/config/config.go:33]: we use `intnrt` as alias (here and elsewhere)

File: test/utils/noderesourcetopologies/noderesourcetopologies.go [hunk 7]
```diff
@@ -321,14 +322,44 @@ func AccumulateNames(nrts []nrtv1alpha2.NodeResourceTopology) sets.String {
...
+}
+
+func FilterByTopologyManagerScope(nrts []nrtv1alpha2.NodeResourceTopology, tmScope string) []nrtv1alpha2.NodeResourceTopology {
+	return filterTopologyManagerPolicy(nrts, "", tmScope)
+}
+func FilterByTopologyManagerPolicyAndScope(nrts []nrtv1alpha2.NodeResourceTopology, tmPolicy, tmScope string) []nrtv1alpha2.NodeResourceTopology {
+	return filterTopologyManagerPolicy(nrts, tmPolicy, tmScope)
+}
+
+func filterTopologyManagerPolicy(nrts []nrtv1alpha2.NodeResourceTopology, tmPolicy, tmScope string) []nrtv1alpha2.NodeResourceTopology {
```
Comment (ffromani) [inline test/utils/noderesourcetopologies/noderesourcetopologies.go:336]: I'd split the function in 2 filters: 1 by scope, 1 by policy and compose them by chaining in `FilterByTopologyManager PolicyAndScope` (yes, this will duplicate a `for` loop, and is not a big deal).

File: test/utils/noderesourcetopologies/noderesourcetopologies.go [hunk 8]
```diff
@@ -434,13 +465,9 @@ func ResourceInfoProviding(resources []nrtv1alpha2.ResourceInfo, resName string,
...
 }
 
-func FilterByPolicies(list []nrtv1alpha2.NodeResourceTopology, policies []nrtv1alpha2.TopologyManagerPolicy) []nrtv1alpha2.NodeResourceTopology {
-	var filteredNrts []nrtv1alpha2.NodeResourceTopology
-	for _, policy := range policies {
-		nrts := FilterTopologyManagerPolicy(list, policy)
-		filteredNrts = append(filteredNrts, nrts...)
-	}
-	return filteredNrts
+// REVIEW - Could avoid this call
```
Comment (ffromani) [inline test/utils/noderesourcetopologies/noderesourcetopologies.go:468]: In general I'm against trivial wrappers. I'd just update the call sites to use `FilterByTopologyManagerPolicy`

**Review by ffromani — COMMENTED** [review]
nice work! few more comments and we're good

**Comment by jlojosnegros** [comment]
Thanks for the review @ffromani 
I have addressed all the comments .

File: internal/noderesourcetopology/attributes.go [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+	TopologyManagerScopeAttribute  = "topologyScopeAttribute"
+)
+
+//   - `restricted`: kubelet only allows pods with optimal NUMA node alignment for
+//     requested resources;
+//   - `best-effort`: kubelet will favor pods with NUMA alignment of CPU and device
+//     resources;
+//   - `none`: kubelet has no knowledge of NUMA alignment of a pod's CPU and device resources.
+//   - `single-numa-node`: kubelet only allows pods with a single NUMA alignment
+//     of CPU and device resources.
```
Comment (ffromani) [inline internal/noderesourcetopology/attributes.go:30]: where is the source for these comments?

File: internal/noderesourcetopology/attributes.go [hunk 10]
```diff
@@ -0,0 +1,43 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package noderesourcetopology
+
+const (
+	TopologyManagerPolicyAttribute = "topologyPolicyAttribute"
```
Comment (ffromani) [inline internal/noderesourcetopology/attributes.go:20]: wrong name, please check https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/noderesourcetopology/README.md#topology-manager-configuration

File: test/e2e/serial/config/config.go [hunk 11]
```diff
@@ -164,10 +165,11 @@ func CheckNodesTopology(ctx context.Context) error {
 		return fmt.Errorf("Following nodes have incoherent info in KubeletConfig/NRT data:\n%s\n", string(prettyMap))
 	}
 
-	snnPodLevelNRTs := e2enrt.FilterTopologyManagerPolicy(nrtList.Items, nrtv1alpha2.SingleNUMANodePodLevel)
+	//TODO - Can look just for single-numa-node policy whatever the scope
```
Comment (ffromani) [inline test/e2e/serial/config/config.go]: in some cases yes. Some testcases however
1. need to run against `single-numa-node` policy but
2. make different logic (by design) depending on `scope`.

So somehow we will need to check both (or to rewrite the tests)

File: test/utils/noderesourcetopologies/noderesourcetopologies.go [hunk 12]
```diff
@@ -321,15 +322,30 @@ func AccumulateNames(nrts []nrtv1alpha2.NodeResourceTopology) sets.String {
...
 	for _, nrt := range nrts {
-		if !contains(nrt.TopologyPolicies, string(tmPolicy)) {
-			klog.Warningf("SKIP: node %q doesn't support topology manager policy %q", nrt.Name, string(tmPolicy))
+		attr, ok := attribute.Get(nrt.Attributes, attrInfo.Name)
+		if !ok {
+			klog.Error("SKIP: node %q doesn't have required attribute %q", nrt.Name, attrInfo.Name)
+			continue
+		}
+		if attr.Value != attrInfo.Value {
+			klog.Warningf("SKIP: node %q doesn't wrong attribute value actual:%q, expected: %q", nrt.Name, attr.Value, attrInfo.Value)
```
Comment (ffromani) [inline test/utils/noderesourcetopologies/noderesourcetopologies.go:346]: this is nice, but now I wonder if we should just remove the one-line wrappers and use this everywhere

File: test/e2e/serial/config/config.go [hunk 13]
```diff
@@ -165,15 +165,9 @@ func CheckNodesTopology(ctx context.Context) error {
...
-	numSnnPodLevelNRTs := len(snnPodLevelNRTs)
-
-	snnContainerLevelNRTs := e2enrt.FilterByTopologyManagerPolicyAndScope(nrtList.Items, intnrt.SingleNUMANode, intnrt.Container)
-	numSnnContainerLevelNRTs := len(snnContainerLevelNRTs)
-
-	if numSnnPodLevelNRTs < minNumberOfNodesWithSameTopology && numSnnContainerLevelNRTs < minNumberOfNodesWithSameTopology {
-		return fmt.Errorf("Not enough nodes with either %q topology (found:%d) nor %q topology (found: %d). Need at least %d", nrtv1alpha2.SingleNUMANodePodLevel, numSnnPodLevelNRTs, nrtv1alpha2.SingleNUMANodeContainerLevel, numSnnContainerLevelNRTs, minNumberOfNodesWithSameTopology)
+	singleNUMANodeNRTs := e2enrt.FilterByTopologyManagerPolicy(nrtList.Items, intnrt.SingleNUMANode)
+	if len(singleNUMANodeNRTs) < minNumberOfNodesWithSameTopology {
+		return fmt.Errorf("Not enough nodes with %q topology (found:%d). Need at least %d", intnrt.SingleNUMANode, len(singleNUMANodeNRTs), minNumberOfNodesWithSameTopology)
```
Comment (ffromani) [inline test/e2e/serial/config/config.go:170]: looks good: please squash in the parent commit - unless there's a clear reason (which I'm missing atm) to keep it separate. If so please describe in the commit message.

**Review by ffromani — COMMENTED** [review]
/hold

looks good, thanks. Need to test it against a cluster. Holding up until that time.

File: internal/noderesourcetopology/attributes.go (hunk 9 above)
Comment (jlojosnegros) [reply internal/noderesourcetopology/attributes.go:30]: From kubelet config package https://github.com/kubernetes/kubelet/blob/6f5021b1251c0e562b5753a402bab61ec4b07596/config/v1beta1/types.go#L374

File: test/e2e/serial/config/config.go (hunk 11 above)
Comment (jlojosnegros) [reply test/e2e/serial/config/config.go]: Well, in this particular case I think we can do so as we are only counting the number of nodes with the wanted topology policy.

File: test/utils/noderesourcetopologies/noderesourcetopologies.go (hunk 12 above)
Comment (jlojosnegros) [reply test/utils/noderesourcetopologies/noderesourcetopologies.go:346]: Sure we can but I think this is much more readable
```
FilterByTopologyManagerPolicy(nrtList.Items, intnrt.SingleNUMANode)
```
than this
```
filterByAttribute(nrtList.Items, nrtv1alpha2.AttributeInfo{Name: e2enrt.TopologyManagerPolicyAttribute, Value: intnrt.SingleNUMANode})

```

And I am pretty sure that the go compiler would be able to optimize the call avoiding unnecessary jumps

File: test/e2e/serial/config/config.go (hunk 11 above)
Comment (ffromani) [reply test/e2e/serial/config/config.go]: yes, in this case I think we can count only the nodes per topology and error out if that number is `< minNumberOfNodesWithSameTopology`

Instead of two check we can just have indeed

```
...
// TODO was here
...
snnContainerLevelNRTs := e2enrt.FilterByTopologyManagerPolicy(nrtList.Items, intnrt.SingleNUMANode)
numSnnContainerLevelNRTs := len(snnContainerLevelNRTs)
if numSnnPodLevelNRTs < minNumberOfNodesWithSameTopology {
...
```

File: test/e2e/serial/config/config.go (hunk 13 above)
Comment (jlojosnegros) [reply test/e2e/serial/config/config.go:170]: I just kept it in a different commit because it is just a minor improvement in a test using the newly created filter functions

File: test/utils/noderesourcetopologies/noderesourcetopologies.go (hunk 12 above)
Comment (ffromani) [reply test/utils/noderesourcetopologies/noderesourcetopologies.go:346]: oneliner-functions which just translate/reshuffle/repack parameters are almost always a smell. In this case I think practicality trumps so let's ignore the smell and go with the current approach.

File: test/e2e/serial/config/config.go (hunk 13 above)
Comment (ffromani) [reply test/e2e/serial/config/config.go:170]: In this case I'm leaning towards squashing - we're mixing mechanical translations with changes anyway, and it's OK (if done sparingly)

File: internal/noderesourcetopology/attributes.go (hunk 10 above)
Comment (jlojosnegros) [reply internal/noderesourcetopology/attributes.go]: Thanks for the comment. 
Changed

File: test/utils/noderesourcetopologies/noderesourcetopologies.go (hunk 12 above)
Comment (jlojosnegros) [reply test/utils/noderesourcetopologies/noderesourcetopologies.go:346]: Well, I am not sure that is a code smell ... I mean that kind of functions could make the code more readable hiding implementation details or "ugly" code compositions. 
In this case the "user" just want to filter a list by a value I do not need to know if that value is an attribute, nor need to build an AttributeInfo struct ... those are implementation details.

Comment (ffromani) [reply test/utils/noderesourcetopologies/noderesourcetopologies.go:346]: I agree in this case is beneficial and improves readability in the calling site (not so sold in the implementation site, but it's good enough).
In general I've become very wary of shallow functions, which trivial-oneliners which repack/reshuffle/rearrange arguments are a prime example of.

File: internal/noderesourcetopology/attributes.go (hunk 9 above)
Comment (ffromani) [reply internal/noderesourcetopology/attributes.go:33]: OK, this content is unlikely to change anytime soon. I'd backlink the original source here (and below for scopes) but not worth resubmitting for this little change.

**Review by ffromani — COMMENTED** [review]
LGTM, nice work. Will add proper lgtm and unhold once tested succesfully against a full cluster.

File: test/utils/noderesourcetopologies/noderesourcetopologies.go [hunk 14]
```diff
@@ -321,15 +322,30 @@ func AccumulateNames(nrts []nrtv1alpha2.NodeResourceTopology) sets.String {
...
 			continue
 		}
-		klog.Infof("ADD : node %q supports topology manager policy %q", nrt.Name, string(tmPolicy))
-		ret = append(ret, nrt)
```
Comment (ffromani) [inline test/utils/noderesourcetopologies/noderesourcetopologies.go:332]: the `append` went missing and should be restored. To prevent this to occurr in the future we can move code in `internal/noderesourcetopologies` and add unit tests (possibly in a future PR)

**Review by ffromani — APPROVED** [review]
/lgtm cancel

File: test/utils/noderesourcetopologies/noderesourcetopologies.go (hunk 14 above)
Comment (jlojosnegros) [reply test/utils/noderesourcetopologies/noderesourcetopologies.go:332]: Thanks for the catch ... 
Yeah need to add some unit testing to avoid this. I will try to keep that in mind in the future.

**Comment by ffromani** [comment]
retested too eatly it seems, https://github.com/openshift/release/pull/41614 not picked up correctly
